### PR TITLE
Wording tweaks

### PR DESCRIPTION
**Pull request by Spin0530**
Still waiting for FAQ and new picture

### CODE REVIEW

**Comment by ender503** [comment]
The FAQ is already removed for temporary on the master branch.
The core-features picture is updated on the master branch.

**Comment by ender503** [comment]
@Spin0530 Is it okay to merge this PR? 😃

**Comment by jserv** [comment]
Change the subject to reflect what you did.

**Comment by ender503** [comment]
Change commit subject or PR subject? 
Maybe the subject can be replaced with "Wording tweaks". 🤔

**Pull request merged**
